### ISSUE TITLE
Jupyter kernel keeps dying and restarting

### ISSUE THREAD

**Issue by IceS2** [yunabe/lgo#21]
Hello, I'm trying to make Igo work. I've installed following the guide. I tested that go is installed, I tested lgo repl and it works (when I run it like ./lgo run).
But in my Jupyter notebook server, the kernel keeps dying and simply doesn't work.
Can you help me out? Thanks!

**Comment by yunabe** [comment]
Thank you for the feedback.

Can you share your environment (OS, Go version, commands you run, etc..) so that I can reproduce the bug?

Also, the kernel usually outputs stack traces to the console where you run `jupyter notebook` when it crashes. This is the example of stack traces with an artificial fatal error. 
![Uploading media-20180202.png…]()
If I can see the stack traces in your environment, it is very helpful for debugging.

**Comment by IceS2** [comment]
Hey @yunabe, thanks for the fast answering (=
I'm sorry for wasting your time, I'm an idiot... I was so focused on solving it that didn't make sense the stacktrace last time I looked (It said that GOPATH wasn't set) but it was set on my environment...
Problem was that I was running the notebook server using supervisord and it wasn't set inside supervisord configuration!

Again, I'm sorry for that actually not being an issue with Igo, it's been a while since I used supervisord and I let that one slip right through ><
