### ISSUE TITLE
Support multi-byte-encoded filenames in prebuilt docker image

### ISSUE THREAD

**Issue by baram204** [yunabe/lgo#25]
If file path or filename has non-ascii character, got errors.

I'm using docker-toolbox on windows 10. and Lgo container python's default character set is below.

```
$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdin.encoding
'ANSI_X3.4-1968'
>>> 
```

And urf-8 character not supported default in python2.

```
>>> import sys
>>> sys.stdin.encoding
'ANSI_X3.4-1968'
>>> b = '가'
>>> b
'\xb0\xa1'

```

So how about updating python version to 3.x ?

**Comment by yunabe** [comment]
> If file path or fileaname has non-ascii character, got errors.

Oh, this is terrible. I did not notice this though I speak a multi-byte-encoded language.

> So how about updating python version to 3.x ?

The docker image relies on Python2.7, not 3.x, just because I'm still using Python2.7 at work. As far as I know, there is no strong reason to Python3.x in lgo docker image.
I plan to fix the filename encoding issue with Python2.7 for the short-term solution. But, as you reported, it might make more sense to migrate Python3.x

**Comment by baram204** [comment]
Ok, If there is no strong reason. I change title to support multi-byte-encoded langes.

**Comment by yunabe** [comment]
Sorry, there was a terrible typo in my previous comment (no strong reason to Python3.x --> no strong reason to use Python2.7).

Anyway, I've updated the Dockerfile and [the prebuilt docker image](https://hub.docker.com/r/yunabe/lgo/tags/). You can use UTF8 filenames now. If you can not, please let me know.

BTW, I was not able to fix this filename issue just by switching to Python3.x for some reason. This is Python [filesystemencoding](https://docs.python.org/3.6/library/sys.html#sys.getfilesystemencoding) issue and it was a little bit different from unicode+ascii encoding hells in Python2.x.
