### ISSUE TITLE
`contrib` bin missing can't install nbextensions properly

### ISSUE THREAD

**Issue by baram204** [yunabe/lgo#27]
I can't install nbextentions below command.

```
jupyter contrib nbextension install --user
```

so can't access nbextends with nbextenstion configurator pannel like below 

![image](https://user-images.githubusercontent.com/11155414/36755301-216ab82a-1c4f-11e8-9775-f863eda7c93a.png)

nbextensions alerady Installed.

```
$ pip install jupyter_contrib_nbextensions
......
Installing collected packages: enum34, six, decorator, ipython-genutils, traitlets, jupyter-core, webencodings, html5lib, bleach, pygments, functools32, jsonschema, nbformat, mistune, testpath, MarkupSafe, jinja2, configparser, entrypoints, pandocfilters, nbconvert, scandir, pathlib2, pickleshare, simplegeneric, backports.shutil-get-terminal-s
......
```

**Comment by baram204** [comment]
try this
```
$ cd ~/.local/bin
$ ./jupyter-contrib-nbextension install --user
```

**Comment by yunabe** [comment]
I'm not sure what was the problem.
We do not pip-install `jupyter_contrib_nbextensions` ([Dockerfile](https://github.com/yunabe/lgo/blob/master/docker/image/Dockerfile)) and that's why we can not execute `jupyter contrib` in the prebuilt docker image.
If you install `jupyter_contrib_nbextensions` with pip, I think you can run `jupyter contrib`.
