### ISSUE TITLE
install_kernel uses python2

### ISSUE THREAD

**Issue by metal3d** [yunabe/lgo#33]
Hello,
I spent 1 hour to find that problem :) Using Fedora 27, "python" is python 2.7. But I used "pip3" to install jupyterlab

I found that you are using a script to install lgo kernel where the first bang line is using "python", I had to change that to "python3". Maybe we must find a way to detect the right version ?

BTW: I'm creating a plot lib that already works well with lgo, I will ask you some questions for that
Other BTW: I guess I will write an article on medium.com to explain my plot lib that can only work with you almightly kernel. Really, you beat gopherlab :)

**Comment by yunabe** [comment]
Thank you for the feedback. Actually, I did not think deeply about the environment where Python2 and Python3 coexist because I still stick to Python2 at work.
I updated README.md and added comments about how to install the kernel configuration with Python2 and Python3. Do you think this comment would have saved your 1 hour if it had been in README.md? Let me know if you have a better idea to avoid this Python version issue.

>BTW: I guess I will write an article on medium.com to explain my plot lib that can only work with you almightly kernel. Really, you beat gopherlab :)

I'm glad you liked my project. I'm looking forward to your post on medium.com :)

**Comment by yunabe** [comment]
I'm closing this bug now. Let me know if you still have a problem.
